version: '3.8'
services:
# PostgreSQL для хранения данных мониторинга
  postgres:
    image: postgres:15-alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: dev123
    volumes:
    # инициализация БД
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitoring -d monitoring"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ClickHouse для аналитики и временных рядов
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports: ["8123:8123"]
    healthcheck:
    # Проверка доступности через HTTP ping endpoint
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MailHog для тестирования email уведомлений
  mailhog:
    image: mailhog/mailhog:latest
    ports: 
      - "1025:1025"  # SMTP порт для отправки писем
      - "8025:8025"  # Web UI для просмотра писем
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports: ["80:80", "443:443"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - postgres
      - clickhouse
      - mailhog
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
