version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: pingtower-postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: monitoring
      POSTGRES_PASSWORD: dev123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitoring -d monitoring"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pingtower-network

  # ClickHouse для аналитики
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: pingtower-clickhouse
    ports: ["8123:8123"]
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pingtower-network

  # MailHog для email
  mailhog:
    image: mailhog/mailhog:latest
    container_name: pingtower-mailhog
    ports: 
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pingtower-network

  # Backend Spring Boot
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: pingtower-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monitoring
      SPRING_DATASOURCE_USERNAME: monitoring
      SPRING_DATASOURCE_PASSWORD: dev123
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pingtower-network

  # Frontend React
  frontend:
    build:
      context: ../frontend/ping-tower
      dockerfile: Dockerfile
    container_name: pingtower-frontend
    depends_on:
      - backend
    networks:
      - pingtower-network

  # Telegram Bot
  bot:
    build:
      context: ../bot
      dockerfile: Dockerfile
    container_name: pingtower-bot
    ports:
      - "5000:5000"
    environment:
      BOT_TOKEN: "7479905970:AAGRDlnda26Aw6Bfbq9HyaPWFmOQt1aAb3o"
      FLASK_PORT: 5000
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    volumes:
      - bot_data:/app/data
    depends_on:
      - mailhog
    restart: always
    networks:
      - pingtower-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: pingtower-nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pingtower-network

volumes:
  postgres_data:
  clickhouse_data:
  bot_data:

networks:
  pingtower-network:
    driver: bridge
