server:
  port: 8080
  servlet:
    context-path: /v1
spring:
  application:
    name: backend
  mail:
    host: localhost
    port: 25
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

# OpenAPI/Swagger configuration
springdoc:
  # api-docs:
  #   path: /v3/api-docs
  #   enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  info:
    title: PingTower API
    version: 1.0.0
    description: |
      PingTower is a comprehensive monitoring and alerting system that helps you 
      keep track of your services' health and availability. This API provides 
      endpoints for managing monitored services, viewing check results, 
      configuring alerts, and managing notification channels.
    contact:
      name: Team Taxisty
      url: https://github.com/Team-taxisty/PingTower

# PingTower Scheduler Configuration
pingtower:
  scheduler:
    instance-name: PingTowerScheduler
    thread-count: 10
    clustered: false
    cluster-checkin-interval: 20000
    misfire-threshold: 60000
    max-retry-attempts: 3
    retry-delay-seconds: 30
    default-timeout-seconds: 30
    auto-start: true
