server:
  port: 8080
  servlet:
    context-path: /v1
spring:
  application:
    name: backend
  mail:
    host: localhost
    port: 25
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    url: /v3/api-docs

# PingTower Scheduler Configuration
pingtower:
  scheduler:
    instance-name: PingTowerScheduler
    thread-count: 10
    clustered: false
    cluster-checkin-interval: 20000
    misfire-threshold: 60000
    max-retry-attempts: 3
    retry-delay-seconds: 30
    default-timeout-seconds: 30
    auto-start: true

# JWT Configuration
jwt:
  secret: pingtower-secret-key-for-jwt-tokens-in-hackathon
  expiration: 86400000

logging:
  level:
    taxisty.pingtower.backend.api.controller.MonitoredServiceController: DEBUG
    org.springframework.security: DEBUG
