spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/monitoring
    username: monitoring
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  # Optional: Mailhog in docker
  mail:
    host: mailhog
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

monitoring:
  clickhouse:
    # Use Docker service hostname, not localhost
    url: jdbc:clickhouse://clickhouse:8123/monitoring?compress=0
    username: default
    password: ""

pingtower:
  telegram:
    bot-service-url: http://python-bot:5000
