openapi: 3.1.0
info:
  title: Pingtower Monitoring API
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
paths:
  /checks:
    get:
      summary: List checks
      parameters:
        - in: query
          name: limit
          schema: { type: integer, default: 50, maximum: 500 }
        - in: query
          name: cursor
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: '#/components/schemas/Check' }
                  next_cursor:
                    type: string
                    nullable: true
        '400': { $ref: '#/components/responses/BadRequest' }
        '500': { $ref: '#/components/responses/InternalError' }
    post:
      summary: Create check
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CheckCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Check' }
        '200':
          description: Idempotent replay (resource already exists)
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Check' }
        '409': { $ref: '#/components/responses/Conflict' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '500': { $ref: '#/components/responses/InternalError' }

  /runs:
    get:
      summary: List runs
      parameters:
        - in: query
          name: check_id
          schema: { type: string, format: uuid }
        - in: query
          name: from
          schema: { type: string, format: date-time }
        - in: query
          name: to
          schema: { type: string, format: date-time }
        - in: query
          name: limit
          schema: { type: integer, default: 1000, maximum: 10000 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: '#/components/schemas/Run' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '500': { $ref: '#/components/responses/InternalError' }

  /notifications/channels:
    post:
      summary: Create notification channel
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateNotificationChannelRequest' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/NotificationChannel' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '500': { $ref: '#/components/responses/InternalError' }
    get:
      summary: List notification channels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: '#/components/schemas/NotificationChannel' }
        '500': { $ref: '#/components/responses/InternalError' }

  /notifications/deliveries:
    get:
      summary: List notification deliveries
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: '#/components/schemas/NotificationDelivery' }
        '500': { $ref: '#/components/responses/InternalError' }

  /notifications/test:
    post:
      summary: Send test notification
      parameters:
        - in: query
          name: channelId
          required: true
          schema: { type: integer, format: int64 }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/TestNotificationRequest' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/NotificationDelivery' }
        '404': { $ref: '#/components/responses/NotFound' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '500': { $ref: '#/components/responses/InternalError' }

components:
  schemas:
    Check:
      type: object
      required: [id, name, type, target, enabled, created_at]
      properties:
        id: { type: string, format: uuid }
        name: { type: string, maxLength: 100 }
        type: { type: string, enum: [HTTP, HTTPS, API_JSON, API_XML] }
        target: { type: string }
        interval_sec: { type: integer, minimum: 1 }
        enabled: { type: boolean }
        created_at: { type: string, format: date-time }
    CheckCreate:
      type: object
      required: [name, type, target]
      properties:
        name: { type: string }
        type: { type: string, enum: [HTTP, HTTPS, API_JSON, API_XML] }
        target: { type: string }
        interval_sec: { type: integer, minimum: 1, default: 60 }
    Run:
      type: object
      required: [id, check_id, started_at, latency_ms, status]
      properties:
        id: { type: string, format: uuid }
        check_id: { type: string, format: uuid }
        started_at: { type: string, format: date-time }
        finished_at: { type: string, format: date-time }
        latency_ms: { type: integer }
        status: { type: string, enum: [UP, DOWN, DEGRADED] }
    CreateNotificationChannelRequest:
      type: object
      required: [type, name]
      properties:
        type: { type: string, enum: [TELEGRAM, EMAIL, WEBHOOK] }
        name: { type: string }
        configuration: { type: string }
        isDefault: { type: boolean }
    NotificationChannel:
      type: object
      required: [id, userId, type, name, isEnabled, isDefault, createdAt]
      properties:
        id: { type: integer, format: int64 }
        userId: { type: integer, format: int64 }
        type: { type: string, enum: [TELEGRAM, EMAIL, WEBHOOK] }
        name: { type: string }
        configuration: { type: string }
        isEnabled: { type: boolean }
        isDefault: { type: boolean }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    NotificationDelivery:
      type: object
      required: [alertId, channelId, status, deliveryMethod, attemptCount, sentAt]
      properties:
        id: { type: integer, format: int64 }
        alertId: { type: integer, format: int64 }
        channelId: { type: integer, format: int64 }
        status: { type: string, enum: [SENT, FAILED] }
        deliveryMethod: { type: string, enum: [TELEGRAM, EMAIL, WEBHOOK] }
        attemptCount: { type: integer }
        errorMessage: { type: string, nullable: true }
        sentAt: { type: string, format: date-time }
        deliveredAt: { type: string, format: date-time, nullable: true }
    TestNotificationRequest:
      type: object
      required: [message]
      properties:
        message: { type: string }
    ErrorResponse:
      type: object
      required: [code, message]
      properties:
        code: { type: string }
        message: { type: string }
        details:
          type: object
          additionalProperties: true
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    NotFound:
      description: Not Found
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    Conflict:
      description: Conflict
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    InternalError:
      description: Internal Server Error
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
