name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
     
    - name: Build Backend
      run: |
        cd backend
        chmod +x gradlew
        ./gradlew build -x test
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build Frontend (ignore warnings)
      run: |
        cd frontend/ping-tower
        npm ci
        CI=false npm run build
        
    - name: Build Success
      run: echo "✅ Build completed!"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: 203.81.208.67
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        timeout: 300s
        script: |
          cd /opt/data/pingtower
          git pull origin main
          cd docker
          docker compose down || true
          docker compose up -d --build
          echo "✅ PingTower deployed successfully!"
          docker compose ps
